using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Assets.TensorFlow.Scripts.Utils
{
    public static class  RunConsoleApp
    {
        public static int RunAndWait(string args, string pythonPath, string workDir, out string log)
        {
            System.Diagnostics.ProcessStartInfo start = new System.Diagnostics.ProcessStartInfo();
            start.FileName = pythonPath;
            start.Arguments = args;
            start.WorkingDirectory = workDir;


            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (System.Diagnostics.Process process = System.Diagnostics.Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    log = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")

                    process.WaitForExit();
                    return process.ExitCode;
                }
            }
        }

    }
}
